### ISSUE TITLE
Add localized text

### ISSUE THREAD

**Issue by bstansberry** [wildfly/wildfly-launcher#8]
EAP has localized text for this artifact, but with it broken out from WildFly Core it will no longer get automagically incorporated. Perhaps we should just add it to this repo. This artifact rarely changes its messages so doing this should be safe enough.

@jamezp WDYT?

**Comment by darranl** [comment]
Once split out is wildfly-launcher using jboss-modules?

**Comment by jamezp** [comment]
I'm not sure we need to worry about localization to be honest. This project is mostly used for testing. The only non-test case I'm aware of is the wildfly-maven-plugin and that's just for starting/stopping the server. I don't think provisioning uses this, but I could be wrong there.
